version: '3'

services:
  #####################
  #reserved_proxy     #
  #####################
  reserved_proxy:
    image: nginx:1.21.4
    ports:
      - 80:80
    volumes:
      - ./local/reserved_proxy/sites-enabled:/etc/nginx/conf.d
  #####################
  #reserved_proxy     #
  #####################

  #####################
  #admin_api          #
  #####################
  admin:
    build:
      context: ./
      dockerfile: ./containerized/ubuntu/Dockerfile
    volumes:
      - ./applications/admin:/var/www
  #####################
  #admin_api          #
  #####################

  #####################
  #user_ui            #
  #####################
  user:
    build:
      context: ./
      dockerfile: ./containerized/ubuntu/Dockerfile
    volumes:
      - ./applications/user/dist:/var/www/public
  #####################
  #user_ui            #
  #####################

  #####################
  #mariadb            #
  #####################
  mariadb:
    image: mariadb:10.5
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
  #####################
  #mariadb            #
  #####################

  #####################
  #mongodb            #
  #####################
  mongodb:
    image: mongo:5.0.5
    ports:
      - 27107:27107
  #####################
  #mongodb            #
  #####################

  #####################
  #redis              #
  #####################
  redis:
    image: redis:6.2.6
    ports:
      - 6379:6379
  #####################
  #redis              #
  #####################

  #####################
  #elasticsearch      #
  #####################
  elasticsearch:
    image: elasticsearch:7.16.2
    ports:
      - 9200:9200
  #####################
  #elasticsearch      #
  #####################